version: '3.1'
services:
  dbpostgresql:
    image: postgres:11.4
    container_name: dbpostgresql
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - "5432:5432"
    networks:
      - mynet
    environment:
      - POSTGRES_PASSWORD=bugtracker
      - POSTGRES_USER=bugtracker
      - POSTGRES_DB=dbbugtracker
      
    restart: unless-stopped
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - mynet
    restart: unless-stopped
    
  app:
    container_name: bugtracker
    image: tomcat:jdk8
    expose:
      - 8080
    restart: unless-stopped
    build: ./
    ports:
      - "8080:8080"
    networks:
      - mynet
    links:
      - "dbpostgresql:dbpostgresql"
    depends_on:
      - dbpostgresql
  
networks:
  mynet: 
    driver: bridge
volumes:
  postgres-data:
  pgadmin:
  