# we are extending everything from tomcat:8.0 image ...

FROM tomcat:jdk8

# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat

COPY target/bug-tracker-ws-0.1.war /usr/local/tomcat/webapps/